### ISSUE TITLE
Run Demo 2th time and not working

### ISSUE THREAD

**Issue by huy99ls01** [NVlabs/STEP#17]
I run demo 1st time in google colab and it's working, but when i try 2th time the demo is not working. This is what I got:

`
Warning: If you want to use fp16, please apex with cuda support (https://github.com/NVIDIA/apex) and update pytorch to 1.0
Warning: If you want to use fp16, please apex with cuda support (https://github.com/NVIDIA/apex) and update pytorch to 1.0
Warning: If you want to use fp16, please apex with cuda support (https://github.com/NVIDIA/apex) and update pytorch to 1.0
Loading pretrain model from /content/drive/MyDrive/STEP/pretrained/ava_step.pth
`

`
Building I3D model...
Building I3D head for global branch...
Building I3D head for global branch...
Building I3D head for global branch...
Building I3D head for context branch...
Datalist len:  978
`

`
THCudaCheck FAIL file=/content/drive/My Drive/STEP/external/maskrcnn_benchmark/csrc/cuda/ROIAlign_cuda.cu line=321 error=209 : no kernel image is available for execution on the device
Traceback (most recent call last):
  File "demo.py", line 229, in <module>
    main()
  File "demo.py", line 122, in main
    history, _ = inference(args, conv_feat, context_feat, nets, args.max_iter, tubes)
  File "/content/drive/My Drive/STEP/utils/utils.py", line 48, in inference
    pooled_feat = nets['roi_net'](conv_feat[:, T_start:T_start+T_length].contiguous(), flat_tubes)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/STEP/models/networks.py", line 45, in forward
    tubes.view(-1, 5).detach())
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/STEP/external/maskrcnn_benchmark/roi_layers/roi_align.py", line 92, in forward
    input, rois, self.output_size, self.spatial_scale, self.sampling_ratio
  File "/content/drive/My Drive/STEP/external/maskrcnn_benchmark/roi_layers/roi_align.py", line 53, in forward
    output = _C.roi_align_forward(input, roi, spatial_scale, output_size[0], output_size[1], sampling_ratio)
RuntimeError: cuda runtime error (209) : no kernel image is available for execution on the device at /content/drive/My Drive/STEP/external/maskrcnn_benchmark/csrc/cuda/ROIAlign_cuda.cu:321
`

**Comment by ghost** [comment]
Hey man, can you please share you colab notebook? Thanks
